---

- name: firewalld activate by source
  firewalld:
    zone: "{{ zone.name }}"
    source: "{{ source }}"
    state: enabled
    permanent: yes
  loop: "{{ zone.sources }}"
  loop_control:
    loop_var: source
  notify: firewalld reload firewalld

...
